config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :users, only: [ :show, :edit, :update ]
  resources :camps do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: [:index, :destroy, :show, :edit, :update] do

  end
  resources :reviews, only: [:edit, :update, :destroy]

  get "camp/:id", to: "pages#camp", as: :my_camp
  get "my_camps", to: "pages#my_camps", as: :my_camps
  put "camp/:id", to: "pages#confirm_booking"
  get "filter", to: "pages#filter", as: :camps_filter
end

app/views/pages/_my_camps.html.erb
  <% @camps.each do |camp| %>
  <%= link_to my_camp_path(camp) do %>
    <% if camp.photo? %>
      <div class="card-prof" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path camp.photo %>');">
    <% else %>
      <div class="card-prof" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path 'background.png' %>'); background-position: 1% 25%;">
    <% end %>
         <div class ="card-title"><%= camp.title %></div>
         <div class= "card-description"> <%= camp.description %></div>
         <div class="card-price"><%= camp.price %>$</div>
      </div>
  <% end %>
<% end %>

app/views/pages/camp.html.erb
<% photo = @camp.photo %>
<div class="banner-detail" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= photo %>');">
  <div class="banner-content">
    <h1><%= @camp.title %></h1>
  </div>
</div>

<div class="btn btn-info"><i class="fa fa-chevron-left" aria-hidden="true"></i><%= link_to ' Back to My Camps ', user_path(current_user) %></div>

<div class="container detail-intro">
  <div class="row">
    <div class= "col-sm-9 col-xs-12 camp-summary">
      <h1><%= @camp.title %></h1>
      <div class="description-look"> <%= @camp.address %></div>
   </div>

   <div class= "col-sm-3 col-xs-12 price-box-container">
    <div class="price-look text-center"><%= @camp.price %>$</div>
    <div class="cta-book text-center">
      <%= link_to 'Edit your Camp', edit_camp_path, class: "btn btn-primary" %>
      <%= link_to 'Delete your Camp', camp_path, method: :delete,  data: { confirm: "Are you sure you want to delete this camp?" }, class: "btn btn-danger" %>
    <br>
    </div>
  </div>
</div>
</div>
  <br>
<!-- Description -->
<div class="container description-camp">
  <div class="row">
    <div class="col-xs-12">
      <h3>Description:</h3>
      <p><%= @camp.description %></p>
    </div>
  </div>
</div>
<!-- Reviews -->
<div class="container reviews-camp">
  <div class="row">
    <div class="col-md-12">
      <h3>Reviews:</h3>
      <% @camp.reviews.each do |review| %>
      <div class="review">
        <div class='avatar-review'>
        <%= image_tag(review.user.photo, class: "avatar-review") %>
        </div>
        <div class='review-body'>
          <h3><%= review.title %></h3>
          <p><%= review.description %></p>
        </div>
        <ul class="list-inline product-controls hidden-sm hidden-xs">
          <% review.rating.times do %>
              <i class="fa fa-star" style="color: #ffb400"></i>
            <% end %>
            <% (5 - review.rating).times do %>
             <i class="fa fa-star" style="color: gray"></i>
            <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
</div>

<!-- BOOKINGS FOR YOUR SURF CAMP -->
<div class="container description-camp">
  <div class="row">
    <div class="col-xs-12">
      <h3>Booking for your surf camp:</h3>
        <br>
      <% @camp.bookings.each do |booking| %>
        <ul>
          <li>
            <%= booking.start_date.strftime('%d/%m/%Y') %> -
            <%= booking.end_date.strftime('%d/%m/%Y') %> -
            <%= booking.surfers %> surfers
            <% if booking.accepted %>
            <%= link_to "Cancel Booking", my_camp_path(@camp, booking: { id: booking.id, accepted: false }), method: :put, class: "btn btn-warning" %>
            <% else %>
            <%= link_to "Confirm Booking", my_camp_path(@camp, booking: { id: booking.id, accepted: true }), method: :put, class: "btn btn-success" %>
            <% end %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/filter.html.erb
<div class="search-list">
 <div class="sw">
    <form action='filter'>
      <input type="search" name="search" class="search-detail" placeholder="<%= params[:search] %>" />
      <button class="go"><span class="entypo-search"></span></button>
      <a href="#" class="logo" title="GMRUI"></a>
    </form>
  </div>
</div>
<div class="row">
  <!--  Camp card - 1/2 -->
 <div class="col-md-5 camp-column">
    <% @camps.each do |camp| %>
    <%= link_to camp_path(camp) do %>
    <% if camp.photo? %>
      <div class="card-list" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path camp.photo %>');">
    <% else %>
      <div class="card-list" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path 'background.png' %>'); background-position: 1% 25%;">
    <% end %>
        <div class ="card-title"><%= camp.title %></div>
        <div class="card-price"><%= camp.price %>$</div>
      </div>
    <% end %>
  <% end %>
  </div>

 <!--  map - 1/2 -->
  <div class="col-md-7" >
<!-- map GA-->
  <div id="map" style="width: 100%; height: 600px;"></div>
  </div>

</div>



<!-- JS GA MAP -->
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({
      provider: {
          styles:
          [{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#F78AE0"}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#E0FCFF"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":-100},{"lightness":45}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#6EB6FF"},{"visibility":"on"}]}]
          },


        internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length >= 1) {
          handler.getMap().setZoom(4);
        }
      });
    });

<% end %>
<% end %>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
   <div class="search"><!-- /search -->
    <div class="search__inner search__inner--up">
      <form class="search__form" action='filter'>
        <input class="search__input" name="search" type="search" placeholder="Where ?"/>
        <span class="search__info">Book your next Surf Camp</span>
      </form>
    </div>
  </div><!-- /search -->
  <div class="map"><!-- /map -->
    <%= image_tag "map.png" %>
    <%= link_to "North-America", camps_filter_path(search: "north-america", radius_km: "2500"), class: "map-button", id: "north-america" %>
    <%= link_to "South-America", camps_filter_path(search: "south-america", radius_km: "2500"), class: "map-button", id: "south-america"%>
    <%= link_to "Europe", camps_filter_path(search: "europe", radius_km: "1800"), class: "map-button", id: "europe"%>
    <%= link_to "Australia", camps_filter_path(search: "australia", radius_km: "1600"), class: "map-button", id: "australia"%>
    <%= link_to "Asia", camps_filter_path(search: "southeast-asia", radius_km: "2000"), class: "map-button", id: "asia"%>
    <%= link_to "Africa", camps_filter_path(search: "africa", radius_km: "3500"), class: "map-button", id: "africa"%>
  </div><!-- /map -->
</div>
</div>
<div class="container text-center">
  <div class="explication">
    <div class="h1-home"> How it works</div>
    <br>
      <div class="row">
        <div class="col-sm-4">
          <div class="discover">
            <h3>Discover</h3>
            <p>Find the bests SurfCamp</p>
            <%= image_tag "discover.png", class: "disco" %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="discover">
            <h3>Contact</h3>
            <p>Book your Surf Camp online</p>
            <%= image_tag "contact.png", class: "disco" %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="discover">
            <h3>Surf</h3>
            <p>Go to your next surf trip</p>
            <%= image_tag "surf.png", class: "disco" %>
          </div>
        </div>
    </div>
  </div>
</div>
  <div class="best-camps text-center">
  <div class="container">
  <div class="h1-home"> Newest SurfCamps</div>
  <br>
  <br>
  <div class="row">
    <% @camps.each do |camp| %>
    <div class="col-xs-12 col-sm-4">
      <%= link_to camp_path(camp) do %>
      <% photo = camp.photo %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= photo %>');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2><%= camp.title %></h2>
        </div>
      </div>
    <% end %>
    </div>
    <% end %>
  </div>
  <br>
  <br>
  <br>

  </div>
  </div>
  <div class="background-for-home">
    <div class="container text-center">
        <div class="home-h2-text"><%= link_to 'See all camps', camps_path %></div>
    </div>
</div>

app/views/pages/my_camps.html.erb
<div class="container">

<h1>My Camps</h1>
  <div class="row">

      <% @camps.each do |camp| %>
      <%= link_to my_camp_path(camp) do %>
        <div class="card">
           <div class ="card-title"><%= camp.title %></div>
           <div class= "card-description"> <%= camp.description %></div>
           <div class="card-price"><%= camp.price %>$</div>
        </div>
      <% end %>
    <% end %>
</div>